### ISSUE TITLE
module 'sklearn' has no attribute 'feature_extraction'

### ISSUE THREAD

**Issue by wunicoleshuhui** [Computational-Content-Analysis-2020/frequently-asked-questions#16]
I have an error when trying load Reddit dataset: module 'sklearn' has no attribute 'feature_extraction'

**Comment by HaoxuanXu** [comment]
I'm having the same problem here. My sklearn is up to date and I can actually import sklearn.feature_extraction on its own, but I still can't run lucem_illud_2020.trainTestSplit()

**Comment by meowtiann** [comment]
Same issue here. Any solutions?

**Comment by vahuja92** [comment]
I did too. I added import sklearn.feature_extraction in the first cell and this worked.

**Comment by bhargavvader** [comment]
Does this work for everyone?

**Comment by bhargavvader** [comment]
@wunicoleshuhui @meowtiann @HaoxuanXu ?
