### ISSUE TITLE
HW5 Key Error 'Sami' : actor_network.nodes['Sami']['lines_spoken']

### ISSUE THREAD

**Issue by wunicoleshuhui** [Computational-Content-Analysis-2020/frequently-asked-questions#26]
When I am trying to run actor_network.nodes['Sami']['lines_spoken'], there is  a KeyError: 'Sami'

**Comment by bjcliang-uchi** [comment]
It might be a bug but you can just change the name to another person who exists in this network

**Comment by bhargavvader** [comment]
@wunicoleshuhui - we fixed this, correct?
