### ISSUE TITLE
Normalizing texts in other languages with lucem_illud_2020

### ISSUE THREAD

**Issue by luisesanmartin** [Computational-Content-Analysis-2020/frequently-asked-questions#29]
Is it possible to use `lucem_illud_2020.normalizeTokens()` for normalizing texts in Spanish or other languages?

**Comment by bhargavvader** [comment]
It is indeed. You would need to download a spaCy language model for that language (https://spacy.io/models/es). I'm going to add an option for users to manually pass their own language model in the next lucem_illud_update.
If you need it right away: check the code for normalising tokens in HW4, and the language model ```nlp = spacy.load('en')``` replace with your spanish model.

**Comment by luisesanmartin** [comment]
Awesome. Thanks!
