### ISSUE TITLE
HW 6 - Error on fetch_newsgroups

### ISSUE THREAD

**Issue by rkcatipon** [Computational-Content-Analysis-2020/frequently-asked-questions#37]
@bhargavvader Hi there! Getting an error on the first cell in the new homework. I keep getting an URL open run time error

![image](https://user-images.githubusercontent.com/56122395/74686346-de047600-5196-11ea-971d-d183ef6522de.png)

**Comment by bhargavvader** [comment]
Hey @rkcatipon ! Are you running this is sinteractive mode maybe? RCC doesn't let you download things when on that mode - run this code to download it without that mode, and once you have the data it should run. Sorry for the super late reply, let me know if it works or is relevant!

**Comment by rkcatipon** [comment]
@bhargavvader No worries! Turns out I just hadn't properly updated lucem illud. Should have closed this issue, thanks for following up though!
